### ISSUE TITLE
Add description to Groups

### ISSUE THREAD

**Issue by mbramson** [ElixirCLE/pairmotron#103]
Groups should have a description field. It's about as simple as that!

- [ ] Add migration to add `description` field to the database
- [ ] Add `description` to `Pairmotron.Group` schema
- [ ] UI
  - [ ] Add `description` field to `web/templates/group/show.html.eex`
  - [ ] Add `description` field to `web/templates/group/form.html.eex`

**Comment by ericworkman** [comment]
Taken care of by #110
