### ISSUE TITLE
Display errors in sign up form

### ISSUE THREAD

**Issue by scottmascio2115** [ElixirCLE/pairmotron#106]
When I initially registered for parimotron using my email address `scottmascio@gmail.com` with password `foo_bar` I was under the impression that my account was created because no errors were thrown.

When I went to sign in I was unable too. Turns out my account wasnt created.

I am not sure why it wasnt created, I assume an error was thrown on the registration page but no error was displayed.

**Comment by scottmascio2115** [comment]
I think you maybe able to close this. I was probably hitting login button not register button from the register page. Now that the login button was removed from the register page we should be good to go.

**Comment by ericworkman** [comment]
@scottmascio2115 Thanks for reporting this! The logs indicate that was likely the case, but it uncovered a different issue as @mbramson discovered. We'll close this as soon as we can merge #109 .
