### ISSUE TITLE
Add CI and make heroku auto deploy after tests pass on master

### ISSUE THREAD

**Issue by mbramson** [ElixirCLE/pairmotron#12]
@Serneum for more info

**Comment by Serneum** [comment]
For Heroku, you will want to add `release: mix ecto.migrate` as the first line in your Procfile. That will automatically run migrations on every deploy

For automatic deploys, go to Heroku, click on the Deploy tab, and connect the app to the GitHub repo. You can then tell Heroku to wait for CI to pass before deploying:
![image](https://cloud.githubusercontent.com/assets/1091716/20181961/2d30639a-a72e-11e6-9da1-14610f319cc6.png)

**Comment by ericworkman** [comment]
Thanks @Serneum

**Comment by Serneum** [comment]
@mbramson will need to [add collaborators](https://devcenter.heroku.com/articles/collaborating#add-collaborators) for anyone that wants to have access to the app in Heroku

For CI, you can probably just copy the NermeSterts [.travis.yml file](https://github.com/ElixirCLE/nermesterts/blob/master/.travis.yml) and change the recipients from myself to @mbramson

**Comment by ericworkman** [comment]
@mbramson This is complete. I setup Travis and got the build to pass. I did not setup any notifications for anyone, though. Heroku is set to migrate on deploy and to deploy master whenever ci passes.

**Comment by ericworkman** [comment]
@mbramson Those last few PRs that you merged all auto-deployed successfully.
