### ISSUE TITLE
Allow users to be toggled active and inactive from the /users index route

### ISSUE THREAD

**Issue by mbramson** [ElixirCLE/pairmotron#25]
It would be great to be able to toggle users active and inactive directly from the /users table, so that we don't have to manually update via the users specific show route.

**Comment by Serneum** [comment]
Take a look at [Nermesterts.User](https://github.com/ElixirCLE/nermesterts/blob/master/web/models/user.ex) and [Nermesterts.PlayerController](https://github.com/ElixirCLE/nermesterts/blob/master/web/controllers/player_controller.ex),

**Comment by mbramson** [comment]
So as per @daveshah 's comments I figured I should specify that after looking at both @Serneum and @daveshah 's PR's, what I'd like to see here is probably a javascripty toggle button for each row, that both indicates that current users status and also enables one-click toggling of that user's active status.

I should totally have been more specific initially.

**Comment by mbramson** [comment]
I'm going to close this card as the /users route no longer exists in favor of the /profile route.
