### ISSUE TITLE
Add Pair Model

### ISSUE THREAD

**Issue by mbramson** [ElixirCLE/pairmotron#3]
Add a pair model that captures a given pairing session. This will be useful for a number of things down the line including histories and preventing users from being paired with users they paired with the week previous, 

At a minimum it would have the following fields:
* Date of Pair
* Many users
  * 2 or more (I wouldn't think there should be any limit)

Some other fields to think about that probably don't make sense yet:
* Subject of the pairing session
* Boolean for whether the pairing session actually occurred

**Comment by ericworkman** [comment]
Can we have this record the year and week of the pair instead of or in addition to the date of the pair?
