### ISSUE TITLE
Add the ability to state what you have paired on

### ISSUE THREAD

**Issue by mbramson** [ElixirCLE/pairmotron#32]
This could either just be a string field on the Pair model, or perhaps a link to a specific project. I think that it should at the very least have a string field so that we gain some metrics on what users have been pairing on.

This would necessitate a new "post-pair" UI. Perhaps this would be accessible from the main /pairs route?

You should only be able to post about a pair that you actually participated in.

**Comment by daveshah** [comment]
What do you think about making this tag based? That's sort of what I had in mind - meaning it would prompt you with already entered 'tags', but you could make your own if one didn't exist.
This would allow for multiple tags as well - for times when you might pair not only on `Ruby`, but you also might want to tag it with `Rails` or `RSpec` , `Javascript` etc...
