### ISSUE TITLE
Fix repairify deleting pairs when nothing changes

### ISSUE THREAD

**Issue by mbramson** [ElixirCLE/pairmotron#57]
Currently when the repairify button is clicked, all pairs are deleted, and then new ones are created. If nothing changes about the users in the pool of active users, the same pairs are created, but the original pairs in the database are still deleted. Not only is this a bit wasteful, but it has the side effect of deleting any retrospectives that have been completed for any pairs in that week.

It would be nice to have some sort of mechanism for retaining the pairs in the database in the case that the pool of active users hasn't changed so that the retrospectives aren't deleted for no apparent reason. If the pool of users has changed, then deleting the retrospectives is fine, as the most people will likely be paired with someone else.

**Comment by ericworkman** [comment]
Closes as this was fixed by #81
