### ISSUE TITLE
Implement group-specific pairs

### ISSUE THREAD

**Issue by mbramson** [ElixirCLE/pairmotron#83]
Pairs should not be global, they should be filtered by group. This might mean that the route to get to pairs changes.

To get to the pairs for a specific group, the route should be /groups/:group_id/pairs. I don't think that this should deprecate the /pairs route, perhaps this just redirects to the first group's (or some default group specified by the user in the future) pairs.

This will involve adding an association between pairs and groups.

This work should be decoupled from the work to redesign the pairing engine currently being spearheaded by @ericworkman.

**Comment by ericworkman** [comment]
Completed by #88
